config/routes.rb
Rails.application.routes.draw do
 
  root 'epicenter#feed'

  get 'show_user'=>'epicenter#show_user'

  get 'now_following'=>'epicenter#now_following'

  get 'unfollow'=> 'epicenter#unfollow'

  get 'all_tweets'=> 'tweets#index'

  post 'epi_tweet'=> 'epicenter#epi_tweet'

  get 'tag_tweets'=> 'epicenter#tag_tweets'

  get 'all_users'=> 'epicenter#all_users'

  get 'following'=> 'epicenter#following'

  get 'followers'=> 'epicenter#followers'

  resources :tweets
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tag.rb
class Tag < ApplicationRecord

	has_many :tweet_tags
	has_many :tweets, through: :tweet_tags
	

	def show
		@tag = Tag.all
	end

end

app/models/tweet.rb
class Tweet < ApplicationRecord

	belongs_to :user

	has_many :tweet_tags
	has_many :tags, through: :tweet_tags

	before_validation :link_check, on: :create

	validates :message, presence: true, length: {maximum: 140, too_long: "A tweet is only 140 max. Everybody knows that!"}, on: :create

	after_validation :apply_link, on: :create
	private

		def link_check
			check = false
			if self.message.include?"http"
					check = true
			end

			if check == true
				arr = self.message.split
				index = arr.map{ |x| x.include? "http"}.index(true)
				self.link = arr[index]

				puts '-----------------------'
				puts self.link
				puts '------------------------'
				if arr[index].length >23
					arr[index] = "#{arr[index][0..20]}..."
				end

				self.message = arr.join(" ")
			end
		end

		def apply_link
			arr = self.message.split
			index = arr.map {|x| x.include? "http"}.index(true)

			if index
				url = arr[index]
				arr[index] = "<a href='#{self.link}' target='_blank'>#{url}</a>"
			end

			self.message =arr.join(" ")

		end

end

app/models/tweet_tag.rb
class TweetTag < ApplicationRecord

	belongs_to :tweet
	belongs_to :tag

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

     has_many :tweets
    
     mount_uploader :avatar, AvatarUploader

     validates :username, presence: true, uniqueness: true

     serialize :following, Array

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

  	before_action :authenticate_user!

  	include TweetsHelper
   
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name, :bio, :location, :avatar, :following])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name, :bio, :location, :avatar, :following])
  end

end

app/controllers/epicenter_controller.rb
class EpicenterController < ApplicationController
  
  include TweetsHelper

  def feed
  	@following_tweets =[]

  		Tweet.all.order(created_at: :desc).each do |tweet|
  				if current_user.following.include?(tweet.user_id) || current_user.id == tweet.user_id
  					@following_tweets.push(tweet)
  				end
  		end
  end

  def show_user
    @user = User.find(params[:id])
  end

  def now_following
      current_user.following.push(params[:id].to_i)
      current_user.save

      redirect_to show_user_path(id: params[:id])
  end

  def unfollow
    current_user.following.delete(params[:id].to_i)
    current_user.save

    redirect_to show_user_path(id: params[:id])
  end

  def epi_tweet
    @tweet =Tweet.create(message: params[:tweet][:message], user_id: params[:tweet][:user_id].to_i)

    @tweet = get_tagged(@tweet)
    @tweet.save

    redirect_to root_path
  end

  def tag_tweets
    @tag = Tag.find(params[:id])
  end

  def all_users
    @users = User.order(:name)  
  end

  def following
    @user = User.find(params[:id])
    @users = []

    User.all.each do |user|
      if @user.following.include?(user.id)
        @users.push(user)
      end
    end
  end

  def followers
    @user = User.find(params[:id])
    @users = []

    User.all.each do |user|
      if user.following.include?(@user.id)
        @users.push(user)
      end
    end
  end
  


end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  include TweetsHelper

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  
  # POST /tweets
  # POST /tweets.json
  def create
      @tweet = Tweet.create(tweet_params)

      @tweet = get_tagged(@tweet)


    ##create action continues below

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:message, :user_id, :link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/epicenter_helper.rb
module EpicenterHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper



	def get_tagged(tweet)
		message_arr = Array.new
		message_arr = tweet.message.split
	
		message_arr.each_with_index do |word, index|
			
			if word[0] =="#"
        #create new instance of Tag
        
        if Tag.pluck(:phrase).include?(word.downcase)
          #save that tage as a var (to  use in TweetTag creation)
          tag = Tag.find_by(phrase: word.downcase)
        else
          #create a new instance of the tag
          tag = Tag.create(phrase: word.downcase)
        end
        tweet_tag = TweetTag.create(tweet_id: tweet.id, tag_id: tag.id)
        message_arr[index] = "<a href='/tag_tweets?id=#{tag.id}'>#{word}</a>"
      end
    end

    # PUT THE TWEET BACK TOGETHER
    tweet.message = message_arr.join(" ")	
    	puts'----------------'
			puts tweet.message
			puts'---------------'
    return tweet

	end

  def hot_tags
    tags = Tag.order(created_at: :desc).limit(4)
    return tags
  end

  def top_tweeter
    tweets = Tweet.all
    if tweets.length > 0
      user_id = Tweet.all.group_by { |h| h['user_id']}.to_a.max_by {|x| x[1].length}.first
    
      user = User.find(user_id)
      return user
    end
  end

  def hot_tags
    tweets = TweetTag.all
    if tweets.length>0
      tag_arr = []
      tag_ids = []
      count =0

        tags = TweetTag.all.group_by { |h| h['tag_id'] }


  end

  def top_tweets
    tweets = Tweet.all
      if tweets.length > 0
        user_id = Tweet.all.group_by { |h| h['user_id']}.to_a.max_by {|x| x[1].length}.first

        tweets = Tweet.where(user_id: user_id)
        return tweets.length
      end
  end

  def total_followers
    user = User.find(current_user.id)
    followers =[]

    User.all.each do |followers|
      if followers.following.include?(user.id)
        followers.push(follower)
      end
    end

    return followers.length
  end
end

app/views/epicenter/_user_lists.html.erb
<div class="row">
  <% @users.each do |user| %>
    <div class="col-md-3">
      <div class="well user-list-wells">
        <div class="row">
          <div class="col-md-6">
            <% if user.avatar.url != nil  %>
            <%= image_tag user.avatar.url, class: "show-pic" %>
            <% end %>
          </div>
          <div class="col-md-6">
            <p>
              <% if current_user.following.include?(user.id) %>
                <%= link_to "Following", unfollow_path(id: user.id), class: "btn btn-primary unfollow-btn" %>
              <% else %>
                <% if current_user.id != user.id %>
                  <%= link_to "Follow", now_following_path(id: user.id), class: "btn btn-primary" %>
                <% end %>
              <% end %>
            </p>
          </div>
        </div>
        <div class="row">
          <%= link_to show_user_path(id: user.id) do %>
            <h3><%= user.name %></h3>
            <p>@<%= user.username %></p>
          <% end %>
          <p>
            <%= user.bio %>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/epicenter/all_users.html.erb
<h1>Here's All Users</h1>
<%= render'user_lists' %>

<%= link_to "Home", root_path, class: 'btn btn-info' %>

app/views/epicenter/feed.html.erb
<h1>@<%= current_user.username %>'s Tweeter Page</h1>


<%= form_for Tweet.new, url: {action: "epi_tweet"} do |f| %>
	<%= f.text_field :message, class: "form-control" %>
	<%= f.hidden_field :user_id, value: current_user.id %>
	<%= f.submit "New Tweet", class: "btn btn-info" %>

<% end %>



<h4>Here is what your "friends" are saying</h4>
<div>
	<% @following_tweets.each do |tweet| %>

			<div class="well">
				<div class="row">
					
					<div class="col col-lg-2 col-md-3 col-sm-4 col-xs-4">
						<% if current_user.avatar.url != nil %>
						<%= image_tag tweet.user.avatar.url, class: 'show-pic' %>
						<% end %>
					</div>
					
					<div class="col col-lg-10 col-md-9 col-sm-8 col-xs-8">
 						<p>
 							<% if Time.now - tweet.created_at <86400  %> 
 								<%= time_ago_in_words(local_time(tweet.created_at)) %> ago,
							<% else %>
 								<%= tweet.created_at.strftime('%b%e') if Time.now - tweet.created_at > 86400 %>,
							<% end %>

 							@<%= link_to tweet.user.username, show_user_path(id: tweet.user.id) %> said...</p>
						<p class="well"> <%= tweet.message.html_safe %></p>
					</div>

				</div>
			</div>
	<% end %>
</div>

app/views/epicenter/followers.html.erb
<h1><%= @user.name %>'s Followers</h1>
<%= render 'user_lists' %>

<%= link_to "Back", show_user_path, class: 'btn btn-info' %>

app/views/epicenter/following.html.erb
<h1><%= @user.name %> is Following</h1>
<%= render 'user_lists' %>

<%= link_to "Home", root_path, class: 'btn btn-info' %>

app/views/epicenter/now_following.html.erb
<h1>Epicenter#now_following</h1>
<p>Find me in app/views/epicenter/now_following.html.erb</p>

app/views/epicenter/show_user.html.erb
<h1>Here is information about @<%= @user.username %></h1>


<!-- FOLLOWING ? -->
<p>
	<% if current_user.following.include?(@user.id) %>
				<%= link_to "Following", unfollow_path(id: @user.id), class: "btn btn-info unfollow-btn" %>
			<% else %>
				<% if current_user.id != @user.id %>
					<%= link_to "Follow", now_following_path(id: @user.id), class: "btn btn-primary" %>
				<% end %>
	<% end %>
</p>



<!-- NEW TWEET -->
<div>
	<%= form_for Tweet.new, url: {action: "epi_tweet"} do |f| %>
		<%= f.text_field :message, class: "form-control" %>
		<%= f.hidden_field :user_id, value: current_user.id %>
		<%= f.submit "New Tweet", class: "btn btn-info" %>

	<% end %>
</div>

<%= link_to "#{@user.name}'s Followers", followers_path(id: @user.id), class: "btn btn-warning"%>
<%= link_to "#{@user.name} is following", following_path(id: @user.id), class: "btn btn-warning" %>


<% @user.tweets.each do |tweet| %>
		<div class="well">
			<div class="row">
					<div class="col col-lg-2 col-md-3 col-sm-4 col-xs-4">
				<%= image_tag tweet.user.avatar.url, class: "show-pic"  %>
					</div>
					<div class="col col-lg-10 col-md-9 col-sm-8 col-xs-8">
					<p><%= time_ago_in_words(local_time(tweet.created_at)) %> ago, @<%= link_to tweet.user.username, show_user_path(id: tweet.user.id) %> said...</p>
				<p class="well">	<%= tweet.message.html_safe %></p>
					</div>
		</div>
	</div>
<% end %>

app/views/epicenter/tag_tweets.html.erb
<div>
	<h1>Tag <%= @tag.phrase %></h1>
</div>

<div class="row">
<!-- A plce for current user stats -->
	<div class="well">

		<% @tag.tweets.order(created_at: :desc).each do |tweet| %>
			<p>
				<h3><%= @tag.phrase %></h3>
				<%= tweet.user.name %> <%= link_to "@#{tweet.user.username}", show_user_path(id: tweet.user_id) %>
				 • <%= time_ago_in_words(tweet.created_at) %>
			</p>
			<p>
				<%= tweet.message.html_safe %>
			</p>
			<% end %>
	</div>
</div>

app/views/epicenter/unfollow.html.erb
<h1>Epicenter#unfollow</h1>
<p>Find me in app/views/epicenter/unfollow.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweety</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div id="wrapper">
    	<div class='container'>
    <!-- NAV -->
          <nav class="navbar navbar-expand-lg navbar-light bg-light">

    <!-- NAV BRAND -->
           <%= link_to "Tweety Tweet Tweet", root_path, class: "navbar-brand" %>
    <!-- NAV TOGGLE BUTTON -->
             <button class="nav-btn pull-right navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="true" aria-label="Toggle navigation">
            <span class="glyphicon glyphicon-menu-hamburger"></span>
            </button>

            <div class=" collapse navbar-collapse" id ="navbarTogglerDemo02" >
     <!-- LINKS IN NAV -->
              <ul class="navbar-nav mr-auto mt-2 mt-md-0">

                <li class="nav-item">
              <%= link_to "New tweet", new_tweet_path, class: "nav-link" %>
                </li>
                

                <li class="nav-item">
                 <%= link_to "All tweets", all_tweets_path, class: "nav-link" %> 
                </li>
<!-- Users -->
                 <li class="nav-item">
                      <%= link_to "All Users", all_users_path, class: "nav-link" %>
                </li>

  <!-- Devise -->
                 <% if user_signed_in? %>
                     <!-- Edit Profile -->
                    <li class="nav-item">
                        <%= link_to 'Edit Profile', edit_user_registration_path, class: "nav-link" %>

                    </li>

                   

                    <li class="nav-item">
                    <!-- Devise Sign Out -->   
                           <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>

                    </li>

                    <li class="nav-item">
                          <!-- AVATAR -->
                      <% if current_user.avatar.url != nil %>
                     <%= image_tag current_user.avatar.url, class: "thumb" %>
                     <% end %>

                    </li>

                <% end %>
              </ul>
      
              </div>

       
          </nav>
<!-- USER INFO -->

  <% if user_signed_in? %>
        <div class="well side-info col col-lg-2 col-md-2 col-sm-3">
            
              <div >
                <% if current_user.avatar.url != nil %>
                <p><%= image_tag current_user.avatar.url, class: 'show-pic' %></p>
                <% end %>
              </div>
              <div >
                
                <p><strong>Name: </strong><%= current_user.name %></p>

                <p><strong>Location: </strong><%= current_user.location %></p>

                <p><strong>Bio: </strong><%= current_user.bio %></p>
              </div>
<!-- USER STATS -->
              <div>
                <p><strong>Number of Tweets: </strong><%= current_user.tweets.length %></p>
            
                <p><strong>Following: </strong><%= link_to current_user.following.length, following_path(id: current_user.id) %></p>

                <p><strong>Followers: </strong><%= link_to total_followers, followers_path(id: current_user.id) %></p>

              </div>

        </div>

    <!-- FEED -->
        <div class="col col-lg-7 col-md-7 col-sm-6">
        <%= yield %>
        </div>

    <!-- TAGS THAT ARE HOT TODAY-->
    	 <div class="well side-info col col-lg-3 col-md-3 col-sm-3">
          <div>
            <h2>#HotTags</h2>
            
            <% hot_tags.each do |tag| %>
              <%= link_to tag.phrase, tag_tweets_path(id: tag.id) %>

            <%end %>

          </div>
      
<!-- HOTTEST TWEETER -->
          <div> 
          <h2>@Top Tweeter</h2>

          <%= link_to "@#{top_tweeter.username}", show_user_path(id:top_tweeter.id) %> with <%= top_tweets %> tweets!

          </div>  

      </div>

  <% else %>
      <%= yield %>
  <% end %> 

      <!-- END -->

      </div>
    </div>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :message %>
    <%= form.text_field :message, id: :tweet_message, class: 'form-control' %>
  </div>

  <div class="form-group">

    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-info" %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Change dat tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tweets</h1>

<!-- NEW TWEET FORM-->


<!-- FEED -->
  <% @tweets.order(created_at: :desc).each do |tweet| %>
       
    <div class="well">
     <div class="row">
          
          <div class="col col-lg-2 col-md-4 col-sm-3 col-xs-3">
            <% if current_user.avatar.url != nil %>
              <%= image_tag tweet.user.avatar.url, class: 'thumb' %>
              <% end %>
            </div>
            <div class="col col-lg-10 col-md-8 col-sm-9 col-xs-9">
              <p> <% if Time.now - tweet.created_at <86400  %> 
                <%= time_ago_in_words(local_time(tweet.created_at)) %> ago,
              <% else %>
                <%= tweet.created_at.strftime('%b%e') if Time.now - tweet.created_at > 86400 %>,
              <% end %>
              

                @<%= link_to tweet.user.username, show_user_path(id: tweet.user.id) %> said...</p>

              <p class="panel"><%= tweet.message.html_safe %></p>
          </div>
       <div class="row">
          
             <p class="link col col-lg-4 col-md-4 col-sm-4 col-sm-4"> <%= link_to 'Show', tweet, class: "btn btn-info" %></p>
             <p class="link col col-lg-4 col-md-4 col-sm-4 col-sm-4"> <%= link_to 'Edit', edit_tweet_path(tweet), class: "btn btn-info"  %></p>
             <p class="link col col-lg-4 col-md-4 col-sm-4 col-sm-4"> <%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-info"  %></p>
          
        </div>
      </div>
     </div>

    
  <% end %>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>What's on your mind?</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>


<p><%= image_tag @tweet.user.avatar, class: 'show-pic' %>	
</p>

<h2> @<%= @tweet.user.username %> said ...
</h2>

<div class="well">
	<p>
	  <%= @tweet.message.html_safe %>
	</p>
</div>



<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>